version: '2.2'

networks:
  default:
    name: monitor-network
    external: true

services:
  db:
    container_name: influxdb2
    image: influxdb:2.1.1
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=monitor
      - DOCKER_INFLUXDB_INIT_BUCKET=monitor
    volumes:
      - ./config.yml:/etc/influxdb2/config.yml:ro
      - ./data/:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - default