version: '2.2'

networks:
  default:
    name: monitor-network
  # 根据情况选择是否使用服务发现
  # consul-network:
  #   external: true
services:
  grafana:
    # https://grafana.com/docs/grafana/latest/administration/configure-docker/
    image: grafana/grafana:8.2.5
    container_name: grafana
    restart: always
    ports:
      # 对外暴露端口配置, 建议外部使用nginx等进行反向代理使用
      - "80:3000"
    volumes:
      # grafana的配置信息, 主要包括grafana.ini配置文件
      - ./config/grafana:/etc/grafana
      # grafana持久化信息, 包含plugin、database
      - ./data/grafana:/var/lib/grafana
    networks:
      - default

  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus:/etc/prometheus/:rw
      - ./data/prometheus:/prometheus/:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=4w'
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/etc/alertmanager/
      - ./data/alertmanager:/alertmanager/
    networks:
      - default

  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: on-failure
    command:
      - '--persistence.file=/pushgateway/pushgateway.data'
    ports:
      - "9091:9091"
    volumes:
      - ./data/pushgateway/data:/pushgateway
    networks:
      - default
