version: '2.2'

networks:
  default:
    name: monitor-network
    external: true

services:
  db:
    image: redis:6.2.6
    container_name: redis
    restart: always
    volumes:
      - ./data/:/data:rw
      - ./redis.conf:/etc/redis.conf:rw
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis.conf"]
    networks:
      - default