version: '2.2'

networks:
  default:
    name: monitor-network
    external: true

services:
  db:
    container_name: influxdb1
    image: influxdb:1.8.10
    restart: always
    environment:
      - INFLUXDB_DB=monitor
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/:/var/lib/influxdb:rw
    ports:
      - "8083:8083"
      - "8086:8086"
    networks:
      - default