version: '2.2'

networks:
  default:
    name: monitor-network
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus/:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=4w'
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml/:ro
      - ./data/alertmanager:/alertmanager/:rw
    networks:
      - default

  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: on-failure
    command:
      - '--persistence.file=/pushgateway/pushgateway.data'
    ports:
      - "9091:9091"
    volumes:
      - ./data/pushgateway/data:/pushgateway:rw
    networks:
      - default
